### ISSUE TITLE
Make sure we're capturing the right metrics for Safety First videos

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#919] opened 2017-06-01 17:12 UTC
I believe we want to be tracking the following metrics:
 - site visits / marketing channels
 - page views
 - video completion rates
 - shares
 - subscriptions

@ScottDowne and @vojtechmzl - can  you help make sure we have everything in place to track all of the above when we launch the Safety First site and start promoting the videos?

**Comment by vojtechsedlak** [comment] 2017-06-05 20:38
Hey @ScottDowne, the only events that I think could be added are:

- people clicking play on a given video (ideally the params for the event would be Category=Video, Action=Video Started, Label=[name of video])
- end of a video (params Category=Video, Action=Video Ended, Label=[name of video])
- clicks on share buttons (same params as usual category=Social, Action=Clicked Share Button, Label=[social network name|email]

Please let me know how I can help with implementing those. Thanks!

**Comment by ScottDowne** [comment] 2017-06-05 20:46
Thanks, seems simple enough.

**Comment by ScottDowne** [comment] 2017-06-06 17:59
Updated, added video metrics.

Can test on staging here: https://advocacy-mozilla-org-staging.herokuapp.com/en-US/safety

Going to add a metrics QA list here (@vojtechmzl feel free to add anything I missed that should be here), for things that should work:

- [x] Generic page navigation/view/bounce metrics.
- [x] Video play/end metrics
- [x] Form metrics, errors (email empty, email invalid, privacy policy error, signup success)
- [x] Share button metrics.

**Comment by hannahkane** [comment] 2017-06-12 17:38
Anything else here, or are we good to close?

**Comment by ScottDowne** [comment] 2017-06-12 19:24
I pinged @vojtechmzl to let him know it's on prod, and metrics should be firing. He should already have some data to confirm everything's working.

Maybe let him close this, if not we can.

**Comment by vojtechsedlak** [comment] 2017-06-12 20:44
All events are firing as intended, so closing this ticket. Thanks!

**Closed as completed by vojtechsedlak** 2017-06-12 20:44 UTC
