### ISSUE TITLE
Localizations of FAQ

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#396] opened 2016-09-16 21:55 UTC
Detailed description of work: Once tickets #385 and #389 are complete, then hand off collateral to L10N for translation.

_Start date: October 1, 2016_ 
_Due date: October 17, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment] 2016-10-17 05:45
Duplicate of #394

**Closed as completed by valianttry** 2016-10-17 05:45 UTC
Labels: L10N, P1, Fundraising
