### ISSUE TITLE
Case to Give/Impact - Infographic/online "brochure"

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#406] opened 2016-09-17 19:44 UTC
Detailed description of work: Create a piece with copy and design to explain to potential donors where their dollars are put to work. Would also be a good showcase to current donors to show their support has impact

_Start date: October 3, 2016_ 
_Due date: October 28, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @KevZawacki (since I hear you're already working on something for this)

**Comment by KevZawacki** [comment] 2016-09-19 12:23
@stephaniemcv I am! See #247. Very similar -- perhaps the same thing.

**Comment by valianttry** [comment] 2016-10-07 06:05
Duplicate of #247 so closing this one.

**Closed as completed by valianttry** 2016-10-07 06:05 UTC
Labels: P2, Fundraising, design, copy
