### ISSUE TITLE
Maker Party Create Event/Log in Page only partially localizing

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#579] opened 2016-10-11 15:42 UTC
Detailed description of work: Chrome incognito, ES, none of the fields on the form localized.

_Start date: October 11, 2016_ 
_Due date: October 11, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.
![10_10_es-not-localized](https://cloud.githubusercontent.com/assets/11812272/19277453/9d53ea1e-8f8e-11e6-928a-bc8d339e446e.jpg)

CC:

**Comment by gholme4** [comment] 2016-10-12 15:51
@stephaniemcv @valianttry There is no bug here. These strings need to be translated in Bablic.

**Comment by valianttry** [comment] 2016-10-12 16:18
@TheoChevalier can you help? I believe the spreadsheet we have for kontextor has the translations here in the "Maker Party MISSING" tab:
https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=1686088055

**Comment by TheoChevalier** [comment] 2016-10-12 17:31
Looks like we also need to push a lot of strings from here https://github.com/mozilla/advocacy.mozilla.org/blob/master/locales/en-US/copyright-petition.properties#L52-L97
 I’m not sure what’s the most reliable way of catching all the strings that need to be updated (for instance, error messages). I’m afraid it means digging the code

**Comment by peiying2** [comment] 2016-10-12 19:21
There are two pieces from what I understand: one got mixed up with the petition text like you mentioned here. This should have been split into two separate components.  

Another is under "Learning Network"  https://pontoon.mozilla.org/de/mozilla-learning-network/Event%20Resources/

**Comment by TheoChevalier** [comment] 2016-10-13 16:26
https://makerevents-mozillafoundation.nationbuilder.com/forms/user_sessions/new?locale=fr -> After checking with Zuzanna, Peiying and Andrea, it seems we don’t have the translations, and that the strings in the screenshots below are missing from Bablic (searching from the Text editor returns nothing).
I’m pinging Jennifer to see if something can be done in NB

![capture d ecran 2016-10-13 a 17 15 24](https://cloud.githubusercontent.com/assets/1294206/19357247/b3daab20-9168-11e6-8185-1cda04485457.png)
<img width="1044" alt="capture d ecran 2016-10-12 a 23 57 58" src="https://cloud.githubusercontent.com/assets/1294206/19357443/9ead344c-9169-11e6-9e7b-d922d75004e1.png">
![capture d ecran 2016-10-13 a 17 19 21](https://cloud.githubusercontent.com/assets/1294206/19357459/b501828e-9169-11e6-8b9a-990979607f41.png)

**Comment by jendc123** [comment] 2016-10-13 17:51
Hi @TheoChevalier - we have added all these fields so you can now edit via Bablic.  To access the fields you will need to use the text editor vs. the visual editor.  Go to the MakerParty visual editor > options (it's the gear next to the publish button) > text editor and then you can find the strings.

**Comment by TheoChevalier** [comment] 2016-10-13 18:00
@jendc123  Awesome, thanks! I can see new strings. I’ll let Kontextor know that they can translate and push the strings :)

**Comment by jendc123** [comment] 2016-10-27 18:54
Hi @TheoChevalier - wanted to check and see if we can close this.

**Comment by TheoChevalier** [comment] 2016-10-27 19:01
@jendc123 There are still strings here and there in the forms that can’t be localized, so technically, the issue is still valid… Now the question is is it still worth fixing them?

**Closed as completed** 2017-02-22 21:49 UTC
Labels: bug, L10N, QA Fail
