### ISSUE TITLE
Confirm required and optional fields for signature form

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#150] opened 2016-07-23 17:52 UTC
Confirm what fields are optional vs. required from signers for impact: 

**Andrea's suggestions for the form requirements:**
First Name*
Last Name
Email*
Country\* (can we auto-fill this based on browser settings?)
Postal Code

*required

**Pass through data capture (if possible)**
- language (browser setting or form locale)
- desktop / mobile

**Comment by valianttry** [comment] 2016-07-23 17:52
cc @ScottDowne and @shaghdoosti

**Comment by valianttry** [comment] 2016-07-23 18:21
NOTE: This form and its function must be reviewed and approved by MoCo's data compliance team (Marshal Erwin or Urmika)

**Comment by ScottDowne** [comment] 2016-07-25 14:23
@valianttry I'm assuming this is through nationbuilder.

This are the fields nationbuilder uses for signatures.

![screenshot from 2016-07-25 10-15-22](https://cloud.githubusercontent.com/assets/197334/17104413/d062cf22-5250-11e6-9e75-cb294dc71434.png)

These are the required fields:

![screenshot from 2016-07-25 10-17-06](https://cloud.githubusercontent.com/assets/197334/17104454/f62f755c-5250-11e6-9c27-8fe92123d67f.png)

I have not figured out any way to add fields, remove fields, or make first required or options. This is a question for nationbuilder.

Auto fill country and browser set locale also don't look doable, but should ask nationbuilder this too just in case.

I don't know what the difference between "browser setting or form locale" are, they are the same thing to me.

Mobile seems to be solid.

**Comment by ScottDowne** [comment] 2016-07-25 14:28
I asked those questions, and a couple others via their generic contact us page.

**Comment by a-kilroy** [comment] 2016-07-25 15:28
http://nationbuilder.com/petition_signature_variables
http://nationbuilder.com/petition_page_variables

**Comment by ScottDowne** [comment] 2016-07-25 15:43
Hm, odd, this looks more like an API documentation than a configuration in the page dashboard.

I was looking for a "add input field" button, that would allow me to pick the type and give it a name.

Not sure how I would interface with this yet, but I'll take a poke around. New info can never be bad.

**Comment by a-kilroy** [comment] 2016-07-25 15:45
Ahhh my bad. I read too fast. Check their documentation. It _should_ have want you need. It's a common question.

**Comment by ScottDowne** [comment] 2016-07-25 15:54
Looks like this: http://nationbuilder.com/create_custom_people_fields

I think the reason I'm not seeing it is because "If custom fields have not been enabled in your nation" so looks like it's off by default.

Doesn't look too complex though once enabled, which I'll figure out what's involved with that next.

**Comment by shaghdoosti** [comment] 2016-07-25 17:40
Hey -- So quick thoughts: 

First Name*
Last Name

Instead of First Name/ Last Name as separate fields can we make it Name/Pseudonym? 

Email*
Country\* (can we auto-fill this based on browser settings?)

Postal Code <---not sure this translates to all locales. 

*required

Pass through data capture (if possible)

language (browser setting or form locale)
desktop / mobile

This is a P2/P3 but can we have a field that says why is copyright important to you? Share your story about why you're signing this petition?

**Comment by lovegushwa** [comment] 2016-07-25 17:46
@natalieworth @lovegushwa CC'n designers here.

**Comment by ScottDowne** [comment] 2016-07-26 15:21
@Struggling to get the custom field to be displayed, but that's because it doesn't tell me what's wrong, or do any proper error messages or line numbers for syntax errors.

If I had a syntax error, and it just chokes when trying to save the template with the word "error", and I need to find the line myself.

Once I found that out, it simply won't display my custom field and instead says "Liquid error: test_field is not a valid form field for Signup." right in the page.
![screenshot from 2016-07-26 11-23-02](https://cloud.githubusercontent.com/assets/197334/17144020/618436bc-5323-11e6-9f36-54925e5931f7.png)

I'll keep digging.

**Comment by a-kilroy** [comment] 2016-07-26 15:34
Not sure if you are doing this just to make progress but the agency we hire could/should totally set these fields up for us as part of their scope of work.

**Comment by ScottDowne** [comment] 2016-07-26 15:37
Yeah, I'm assuming the agency does this. I'm just getting familiar with it just in case.

**Comment by natalieworth** [comment] 2016-07-26 17:55
@valianttry Have a makeshift/ editable form field here for figuring these out: https://docs.google.com/presentation/d/1X31GHF9SclchaMY-K4Lo2XvUEAmmGrUjGHht-IHt0Q4/edit#slide=id.g15f801c431_0_58

**Comment by valianttry** [comment] 2016-08-04 06:03
I think we're very close to having this final. We should bring this up with Fission asap to get their feedback. I think based on this chat it should be:
First Name*
Last Name*
Email*
Country\* (can we auto-fill this based on browser settings?)

*required

**Questions:**
- Postal Code <---does this translate to our target locales?
- Can we auto-fill country based on browser locale?
- Can we ask for Name/Pseudonym @shaghdoosti can you say more about why you recommend this approach? Is it because of people who wish to remain anonymous? Would offering an "keep my signature anonymous" checkbox solve this?
- If possible, can we capture language (browser setting or form locale) and whether they are on desktop / mobile (note: We can capture this in the aggregate using Google Analytics I believe. cc @vojtechmozilla for thoughts)
- Can we reserve the option to add a comments text box later on?

**Comment by valianttry** [comment] 2016-08-08 15:37
We want to be able to target people with specific Maker Party emails that will appeal to them, e.g. "parties near you" vs. "parties in your country". We may want to require postal code. Can we require either postal code OR country, or do we need to require both for our target EU locales? Postal code conventions vary by country but I don't know the specifics of postal codes in EU Tier 1 locales (or Tier 2).

**Comment by shaghdoosti** [comment] 2016-08-08 16:20
I'll trust others here, my only flag is if we make postcode optional it might actually be hard to find country data there ie: what if two regions in two different countries have the same postcode? Even though it's suboptimal - I'd go with making country and postcode mandatory but having an explainer box that tells people why were asking for that data.

**Comment by shaghdoosti** [comment] 2016-08-08 16:21
Also @valianttry I think a tick box that makes the signature anyonymous works instead of a pseudonym

**Comment by vojtechsedlak** [comment] 2016-08-08 16:28
Could we have a hidden field that captures the full URL of the given session (including URL parameters)? We will be using utm tags to better understand traffic patterns and the efficiency of different channels in Google Analytics, but having that information saved in SF would help us create cohorts of supporters (e.g. see how people who joined through Facebook in this campaign perform in EOY fundraising). 

I believe some type of a hidden field that captures the URL is generally included on our forms, but it currently strips the parameters (e.g. ?utm_source=facebook etc.). 

Let me know if you have any questions or concerns about this.

**Comment by valianttry** [comment] 2016-08-08 16:31
@vojtechmozilla can you double check with Gareth Cull to make sure this is in line with our privacy / user choice practices? I believe we can collect some of this data -- but perhaps not all.

**Comment by vojtechsedlak** [comment] 2016-08-08 16:59
I've reached out to Gareth and will keep you posted. Thanks!

**Comment by valianttry** [comment] 2016-08-08 17:10
DUE: This task must be completed by **August 10.**

**Comment by a-kilroy** [comment] 2016-08-08 18:09
Agree with the postal code and the full url. Would be nice if it was source and sub source so it's easier to sort. Like source 'facebook' - subsource 'full url' or 'campaign identifiers'

**Comment by natalieworth** [comment] 2016-08-08 18:43
@shaghdoosti If privacy is an issue for some people too, we could have a disclaimer (instead of a checkbox) like this example from UK's petition site:
<img width="717" alt="screen shot 2016-08-08 at 11 40 11 am" src="https://cloud.githubusercontent.com/assets/14876567/17491645/5452339c-5d5d-11e6-9661-75231194aef0.png">
I'm just worried that we already will have 2 checkboxes on the site (1 for opting in to future emails, and the other to understand/ agree to our privacy policy. So perhaps some sort of subtext would make people feel more comfortable about signing if they know their information is not going to be publicly displayed anywhere?

**Comment by valianttry** [comment] 2016-08-10 18:35
We'll need to confer with legal and also Lifecycle marketing on this language and the requirements. We do need to be explicit about how we'll use their data -- I'm not sure we can guarantee that their name will not be public. If we print out signatures and deliver boxes of printouts to a government office, sometimes that then becomes a public record.

**Comment by jessilyndavis** [comment] 2016-08-11 16:16
FWIW - we have a "Source URL" field in SFDC and it'd be awesome if we passed through the URL + all the parameters to it (I thought we were already doing this and there wasn't an issue - but maybe there needs to be a vetting by Gareth + Legal?).

**Comment by pmac** [comment] 2016-08-12 03:36
But "Source URL" only gets added if it's not already populated for a user. So it might not be what they want. Or if this isn't going through basket then I think we shouldn't use "Source URL" since we don't want that overwritten.

**Comment by valianttry** [comment] 2016-08-15 17:30
Finalized fields with Jordan, his designs were sent to Fission.

Final approval from legal and compliance is required, that bug is here:
(Locked down for security reasons)
https://bugzilla.mozilla.org/show_bug.cgi?id=1294881 

![copyfail website](https://cloud.githubusercontent.com/assets/9830371/17672803/11e242f6-62d3-11e6-9878-20f9a8eded7e.png)

**Comment by damiankay** [comment] 2016-08-15 20:59
@pmac @ScottDowne @a-kilroy - has a decision been made Re whether we're going to use Basket as middleware?

**Comment by ScottDowne** [comment] 2016-08-16 00:44
We want to use Basket, it's very helpful.

However, it depends on the fields we plan on saving, if we can use Basket or not, and if we can, we most def should.

**Comment by valianttry** [comment] 2016-08-16 04:24
@ScottDowne that's the final decision? I have to say I'm a little surprised, I thought we were working toward relying more on direct integrations and less on middleware for long term.

**Comment by a-kilroy** [comment] 2016-08-16 07:02
Would be awesome to see the short version write up for the reason for this approach. I suspect that could help us in future integration decisions.

**Comment by ScottDowne** [comment] 2016-08-16 15:02
@valianttry hm, I'm not familiar with that as an explicit decision, or was it just more of a guideline and not a general rule? We can chat more about this, because I would rather weigh pros and cons of each situation and solution, instead of having a generic rule.

@a-kilroy nothing fancy, just me, @cadecairos and Walter from Fission got on a call and they weighed the pros and cons, and in the end, I just took their recommendation.

This decision came down to Basket providing:
- Stability and a handful of assurances that our data makes it into SalesForce. Without Basket, we would be wise to create that level of stability ourselves, which is probably not something we want to be doing if it already exists and has support.
- It's not any harder to integrate with than the direct integration.
- The only reason to not use Basket is if it doesn't do what it is we need it to do.
- The fields I see above are "first name", "last name", "country", and "email". These are fields Basket has supported for a while now. http://basket.readthedocs.io/newsletter_api.html#news-subscribe
- It also supports "lang" and "source_url"
- It's open source, so we can add, change, fork, as needed.
- It's proven in my eyes. We are already using it on donate and advocacy sites, and never had any issues.

**Comment by a-kilroy** [comment] 2016-08-16 15:41
@ScottDowne  Gotcha. Would love to know what it doesn't do since where we are now is definitely not where we'll be in a year. Would be awesome to know we can grow into where we are going with whatever we set up. My biggest question I guess is about custom field support and any integration with Google Analytics.

**Comment by ScottDowne** [comment] 2016-08-16 15:45
Can you expand a bit on integration with Google Analytics, primarily vs direct integration and Google Analytics.

For custom fields, I would rather create a pull request in Basket to add that support, than basically hacking out basket functionality ourselves from the ground up.

**Comment by damiankay** [comment] 2016-08-16 18:06
CC @drewmoto please see above for discussion

**Comment by drewmoto** [comment] 2016-08-17 22:04
Hi All,
If I am following the thread correctly, it seems that we are leaning towards Basket as the middleware/integration point but it has not been confirmed. Who on the Fission side will be making the final recommendation that we can sign off on? 

And as far as the Salesforce side goes, and what objects we will be using for this Petition activity, we will be using the Campaign and Contact Objects, with a Campaign type of "Petition". All signers would be added to the Campaign as a Campaign Member. If they exist, we simply add them to the Campaign. If not, the Contact is created and Added to the Campaign as a Campaign Member. I can provide more documentation around the use case but Salesforce's docs are a pretty good place to start (below). Vojtech started on the data model, I think we just need to refine it to match the Salesforce architecture. 

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_campaign.htm

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_erd_majors.htm

**Comment by damiankay** [comment] 2016-08-19 17:50
Here's the latest update RE integration of Nationbuilder and Salesforce from Fission: 

> The team wasn't able to give Walter direct access to Salesforce so it makes using the Salesforce API difficult. Once Walter learned more about Basket from Scott it was a good option for moving forward under our timeline.

So, unless we can give Walter direct access Basket is our only option. It doesn't appear that using Basket will affect the overall timeline. Please see below: 
- Aug 17  Understanding Basket
- Aug 18-19 Nationbuilder webhook set up using Python on Heroku
- Aug 19-21 Basket integration (basket.mozilla.org) with the code.
- Aug 21-22 Internal Testing to ensure data is being sent

@valianttry @ScottDowne @drewmoto Please ping me today (Aug 19) if you have any concerns.

**Comment by damiankay** [comment] 2016-08-19 22:25
Update: @drewmoto was able to get direct access for Walter Fission, so we're going to move forward with direct integration between Nationbuilder and Salesforce rather than using Basket. 

I'm closing this issue now, as it's morphed from the original purpose. Please re-open if we haven't finalized fields.

**Closed as completed by damiankay** 2016-08-19 22:25 UTC
Labels: data
