### ISSUE TITLE
Adding Bpay payment option

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#638] opened 2016-11-22 17:16 UTC
Donor request for adding Bpay (a payment system that seems to only be used in Australia). 

> Dear Mozilla 
> Wikipedia accepts donations by Bpay. I don't use a credit card on the internet but if you organise Bpay I'll make a donation to you. 

CC: @ScottDowne

**Comment by ScottDowne** [comment] 2016-12-23 16:35
Closing this as a dupe of https://github.com/MozillaFoundation/Advocacy/issues/677

**Closed as completed by ScottDowne** 2016-12-23 16:35 UTC
Labels: Fundraising, donor care
