### ISSUE TITLE
'Other' selection option (under 'Country' form category) displays as error in Firefox desktop/mobile

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#282] opened 2016-08-28 05:13 UTC
Browser: Firefox
Description: Desktop/ mobile versions on Firefox displays 'other' selection under 'Country' as an error state. Only seems to be an issue within Firefox browser.

CC: @damiankay @valianttry @jendc123

**Comment by natalieworth** [comment] 2016-08-28 05:15
<img width="320" alt="screen shot 2016-08-27 at 10 19 13 pm" src="https://cloud.githubusercontent.com/assets/14876567/18031768/ceb519b0-6ca3-11e6-81f9-d162179c0b80.png">

**Comment by jendc123** [comment] 2016-08-29 21:12
@valianttry @damiankay This has been resolved. It's a duplicate of #273 https://github.com/MozillaFoundation/Advocacy/issues/273

**Closed as completed** 2016-08-29 21:22 UTC
Labels: bug, P1, Ready for QA
