### ISSUE TITLE
Build landing page variations for MIA team lead gen test

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#41] opened 2016-05-26 22:18 UTC
MJ Kelly to provide copy changes here to @ScottDowne by end of day today.

**Comment by kellymj** [comment] 2016-05-26 23:16
Hey there,

Here is a doc outlining the copy, layout and URL for the variations. The only potentially tricky one is the third experiment set, which is blank except for a headline and form. 

https://docs.google.com/a/mozilla.com/document/d/1aw0Qo2rdbLnfYuO1BFQQlR29l6TdcEV2aVOSketIPjQ/edit?usp=sharing

I'll be at the airport between 6-7 PT, so ping me if you have any questions at all.

Thanks Scott!

**Comment by ScottDowne** [comment] 2016-05-27 01:03
Cool, I took a quick look just to plan my tomorrow better.

One question I have, is there a timeline for how long we expect these pages to be live?

**Comment by kellymj** [comment] 2016-05-27 06:19
I don't know the answer to that. I do see us iterating on the page(s) into the second half of the year.

**Comment by kellymj** [comment] 2016-05-27 13:15
@HPaulJohnson How doe the GA parameters get set up?

**Comment by ScottDowne** [comment] 2016-05-27 13:29
@kellymj no worries, I was just curious. There probably isn't a restriction on our end for how long these pages can live.

**Comment by ScottDowne** [comment] 2016-05-27 14:44
Everything is on staging right now.

Example: https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/hybrida

Take a look at all of them, and if it looks good, I can move it to production.

**Comment by HPaulJohnson** [comment] 2016-05-27 15:39
@kellymj you can use this tool to setup the GA parameters: 

http://mozilla.github.io/mofo-campaignurl/

The Referral ID/Campaign name is "2016_Encryption" and you'll want to choose 'Paid Ad' as the medium. Let me know if you have any questions.

**Comment by kellymj** [comment] 2016-05-27 17:01
Scott, these look good. One change:

/blanka is missing a headline.
Can you please add this copy above the form in the red headline font:
Sign up for Mozilla email

**Comment by kellymj** [comment] 2016-05-27 17:15
@HPaulJohnson The GA task says "Make sure the submit button is an event that is tracked in GA."

Sorry to beat this down, but I don't fully understand what actually needs to be done. Does this make sense?

**Comment by ScottDowne** [comment] 2016-05-27 17:38
@kellymj My bad, I missed that bit. https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/blanka

Should be good now.

**Comment by kellymj** [comment] 2016-05-27 18:16
Thanks. I took a look at it on my phone, since I read this message there,
and the /blank and /signup pages look wonky. Is that an easy fix?

/hybrid is rending fine.

**Comment by kellymj** [comment] 2016-05-27 18:17
(rendering)

**Comment by ScottDowne** [comment] 2016-05-27 18:42
Yup, it seems to not be very well mobile optimized. Thanks for pointing this out. It's not caused by our new test urls, but just always was busted, it seems.

**Comment by HPaulJohnson** [comment] 2016-05-27 19:14
@kellymj I'm not sure I understand your comment: what's the "GA task"?

@ScottDowne confirmed GA is setup on this page which should include tracking on the submit button.

**Comment by ScottDowne** [comment] 2016-05-27 22:51
I filed the mobile signup page issue here: https://github.com/MozillaFoundation/Advocacy/issues/44

**Comment by kellymj** [comment] 2016-05-27 22:57
What do you think about pushing the /hybrid versions to live in the meantime?

**Comment by ScottDowne** [comment] 2016-05-27 23:00
@kellymj can we push them all, but just not share the signup variants?

**Comment by kellymj** [comment] 2016-05-27 23:02
I'll let the team know the situation, however, each variant is being tested. We wanted to see if there was performance difference when we showed them the video next to the form. 

Do you think the mobile fix will happen?

**Comment by ScottDowne** [comment] 2016-05-27 23:03
@kellymj yeah, I'll try to get to the mobile issues, but might not be tonight.

**Comment by kellymj** [comment] 2016-05-27 23:04
Understood and thanks. We are OOO on Monday for a holiday, and I'll be back online on Tuesday morning.

**Comment by ScottDowne** [comment] 2016-05-27 23:19
@kellymj let me see what I can do about the mobile signup page tonighht, it needs to be fixed in general.

**Comment by ScottDowne** [comment] 2016-05-27 23:43
Pushing a fix to staging, it fixes most of the mobile issues.

**Comment by ScottDowne** [comment] 2016-05-27 23:46
K, should be better now.

**Comment by ScottDowne** [comment] 2016-05-27 23:47
(on staging) https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/blanka

**Comment by kellymj** [comment] 2016-05-27 23:52
boom!

**Comment by ScottDowne** [comment] 2016-05-28 00:02
OK cool, so I'm good to ship this to production?

**Comment by kellymj** [comment] 2016-05-28 00:07
Yes, I just checked all of the versions on my mobile, and they're good to go.
Ship 'em.

**Comment by ScottDowne** [comment] 2016-05-28 00:14
Should be shipped now:

https://advocacy.mozilla.org/encrypt/blanka
https://advocacy.mozilla.org/encrypt/hybrida
https://advocacy.mozilla.org/encrypt/signupb

...etc

**Comment by kellymj** [comment] 2016-05-28 00:36
They're all showing up as a blank blue screen.

**Comment by ScottDowne** [comment] 2016-05-28 00:38
It's cache. Sec I'll get cache busted links.

**Comment by ScottDowne** [comment] 2016-05-28 00:40
Try https://advocacy-mozilla-org-prod.herokuapp.com/encrypt/hybrida

It's where advocacy.mozilla.org updates it's cache. Can be up to 24 hours.

**Comment by kellymj** [comment] 2016-05-28 00:51
All the herokuapp links look great. I'll check the live pages later this
weekend and reconfirm. Thanks!

**Comment by kellymj** [comment] 2016-05-31 17:23
They all look good on mobile and desktop. I think this task is done now. Thanks @ScottDowne !

**Comment by ScottDowne** [comment] 2016-06-02 14:27
Yay :rocket: :guitar: :cake: 

Closing

**Closed as completed by ScottDowne** 2016-06-02 14:27 UTC
Labels: dev

**Comment by kellymj** [comment] 2016-06-02 22:57
@ScottDowne Something seems to have gone wrong with /hybridb

https://advocacy.mozilla.org/en-US/encrypt/hybridb

**Comment by ScottDowne** [comment] 2016-06-03 02:28
Good catch, I had a typo in one of the strings, it's fixed here: https://advocacy-mozilla-org-prod.herokuapp.com/en-US/encrypt/hybridb

Cache is probably going to cause an up to 24 hour delay to see the changes on https://advocacy.mozilla.org/en-US/encrypt/hybridb if you have recently viewed the busted page.

**Comment by ScottDowne** [comment] 2016-06-03 03:11
The cache wasn't bad at all this time. Looks to be fixed updated already.

**Comment by kellymj** [comment] 2016-06-03 16:57
Thanks, seems to be correct now. I wonder if it's possible to make the buttons say "Sign up" instead of "Update my information". I missed that on all the hybrid pages. 

Our media partner also noted that the /hybrid versions aren't triggering a "thank you" page. I'm thinking this isn't a problem in terms of the technical sign up process, but if it's an easy fix to send users to https://advocacy.mozilla.org/en-US/encrypt/signup-complete , I think that would be a better experience.
