### ISSUE TITLE
Update Medium footer link on changecopyright.org

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#268] opened 2016-08-25 11:37 UTC
**Detailed description of work**: 
The Medium link at the bottom of https://changecopyright.org/ currently directs to https://medium.com/mozilla-advocacy. 

![screen shot 2016-08-25 at 7 38 27 am](https://cloud.githubusercontent.com/assets/11045250/17967708/e765f1b4-6a96-11e6-9f28-849dd2040f47.png)

Let's instead direct to https://medium.com/mozilla-advocacy/tagged/copyright

**CC**: 
@HPaulJohnson @ScottDowne

**Comment by ScottDowne** [comment] 2016-08-25 12:12
Done

**Comment by HPaulJohnson** [comment] 2016-08-29 18:44
Looks like this reverted back to old link. A P2, but should be fixed. 

@damiankay

**Comment by damiankay** [comment] 2016-08-29 18:56
Thanks for catching. CC @valianttry @jendc123

**Comment by gholme4** [comment] 2016-09-07 19:46
@damiankay @ScottDowne @KevZawacki I updated the link again.

**Comment by HPaulJohnson** [comment] 2016-09-07 22:49
fix confirmed. closing.

**Closed as completed by HPaulJohnson** 2016-09-07 22:49 UTC
Labels: bug, marcom, P2, dev
