### ISSUE TITLE
Fix Mozilla logo on paypal page

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#630] opened 2016-11-14 17:35 UTC
Detailed description of work:
The Mozilla logo is missing from the paypal checkout page. The logo appears to have lived here: https://learning.mozilla.org/blog/wp-content/uploads/2013/11/mozilla_wordmark_190_60px.png

This came in to donate@  (case 15609): 
> please check your PayPal Checkout page as there ist a Mozilla logo 
> embedded, that is not longer available. 
> Go to 
> https://donate.mozilla.org/de?utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=EOY2016&utm_term=5821&sample_rate=0.01&snippet_name=5821&amount=10&currency=eur&presets=20,10,5,3&frequency=single 
> and click on PayPal 

following the directions give me this through english: 
![image](https://cloud.githubusercontent.com/assets/15040203/20275461/a57488d2-aa66-11e6-89a2-8492d2a36499.png)
and this in german
![image](https://cloud.githubusercontent.com/assets/15040203/20275464/a9f056e8-aa66-11e6-9350-af08c3dffabe.png)

*Start date: November 14, 2016* 
*Due date: December 1, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @ScottDowne @cadecairos @stephaniemcv

**Comment by cadecairos** [comment] 2016-11-14 17:38
We should have hosted this on a CDN, not on a blog :/

if someone gets me an image, I can put it somewhere more appropriate.

**Comment by stephaniemcv** [comment] 2016-11-15 00:09
@lovegushwa Can you assist with a logo? We need to make it pretty before we start asking for donations.

**Comment by ScottDowne** [comment] 2016-11-15 18:06
Why wouldn't we have a logo already around?

**Comment by ScottDowne** [comment] 2016-11-15 18:48
Why not just use https://donate.mozilla.org/assets/images/mozilla.5e83dba715a0469b92071758876f0373.svg

**Comment by stephaniemcv** [comment] 2016-11-15 18:52
works for me, I just didn't know where these assets lived.

**Comment by ScottDowne** [comment] 2016-11-15 19:00
Interesting, when I actually test this, I see:

![paypal_logo_moz](https://cloud.githubusercontent.com/assets/197334/20319367/c460e738-ab3b-11e6-9282-8f19e3ac2621.png)

I'll see if I can reproduce this.

**Comment by ScottDowne** [comment] 2016-11-15 19:03
I see, I'm seeing the micro payments account paypal, which shipped last week.

So this only seems to be broken when the donation amount is roughly above 10$

**Comment by ScottDowne** [comment] 2016-11-24 21:28
It wouldn't accept that image, something about only accepting archaic image formats and sizes.

I just went with the text "Mozilla Foundation" to match our micro account.

Previous links were:
https://blog.webmaker.org/wp-content/uploads/2013/11/mozilla_wordmark_190_60px.png
https://blog.webmaker.org/wp-content/uploads/2013/11/mozilla_wordmark_750_90px.png

If we want anything better, reopen and assign to someone that'll make a logo, and I'll swap the new logo back in.

**Closed as completed by ScottDowne** 2016-11-24 21:28 UTC
Labels: Fundraising
