### ISSUE TITLE
Facebook and Email share messages not localized

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#295] opened 2016-08-29 18:04 UTC
Creating a separate/new ticket for this to bump it to top. It appears that the localization for Twitter share messages has been fixed, but the problem still persists for the Facebook and Email share options. In both cases, those share messages appear in English no matter what language is selected. Given these are our two mostly commonly used options for sharing we need to fix!

**Comment by damiankay** [comment] 2016-08-29 18:31
CC @valianttry @jendc123

**Comment by valianttry** [comment] 2016-08-29 18:50
I believe this is a duplicate of https://github.com/MozillaFoundation/Advocacy/issues/298 -- there is more detail in 298.

**Closed as completed by valianttry** 2016-08-29 18:50 UTC
Labels: bug, P1, Ready for QA
