### ISSUE TITLE
A Thank you to delight donors in January after conclusion of the EOY campaign

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#407] opened 2016-09-17 20:24 UTC
Detailed description of work: At Mozfest, create a video of staff saying thank you to our donors.
-ideas: Large group, shot from above. A selected line of people flip placards over their head that read "We _heart_ our donors!" (Something along those lines), that we can turn into an animated gif

_Start date: October 17, 2016_ 
_Due date: November 18, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment] 2016-10-14 05:14
@stephaniemcv this might be a dupe of #247

**Comment by stephaniemcv** [comment] 2016-10-15 02:14
I updated the title. As it didn't match the description of the work.

**Comment by lovegushwa** [comment] 2017-01-06 19:02
email copy draft:
https://docs.google.com/document/d/1xF7bEqzijxCFRTc5PHr83XkR2i1gZoZ2GQR4sVGyMFU/edit?ts=586da42f

**Comment by natalieworth** [comment] 2017-01-18 01:47
Closing this. Final files are here for future reference:
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0ay1vaXdUdzRLNEE
:1st_place_medal:

**Closed as completed by natalieworth** 2017-01-18 01:47 UTC
Labels: P1, Fundraising, design
