### ISSUE TITLE
Email and FB share links goes to English text in all localized sites

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#298] opened 2016-08-29 18:11 UTC
![screen shot 2016-08-29 at 11 07 46 am](https://cloud.githubusercontent.com/assets/5815317/18061778/e06ec2d8-6dd8-11e6-80b0-83b8a6ef6752.png)

When you click on the Facebook and email share links, it goes to English text (localized for Twitter though).

**Comment by valianttry** [comment] 2016-08-29 18:40
Bablic said they fixed this issue:

On Sat, Aug 27, 2016 at 02:51 AM, "Ishai Jaffe" ishai.jaffe@bablic-05becdd13f84.mail.intercom.io wrote:

```
Hi,
Sorry for the late response. We have limited support on Weekends.
We noticed there was a problem in the Edit External URL, that it included the original domain.
We uploaded a fix for it. Now the twit button on the website works, I've tested in French, Spanish, Polish & German.
```

The problem is fixed for both. But I couldn't confirm that because the email share didn't work in my browser (chrome) even in English.

## 

Ishai   Ishai from Bablic
On Sat, Aug 27, 2016 at 10:19 AM, "Andrea Wood" andrea@mozillafoundation.org wrote:

```
Ishai can you confirm that the error was also fixed for the Facebook share and also for the email message share? We need all three of the "share" buttons to work properly. Thank you so much,
andrea
```

**Comment by Melechuga** [comment] 2016-08-29 18:44
@valianttry Maybe it's just taking some time to switch over...?
You said the email share doesn't work for you; I found that hovering over the buttons will show the text at the bottom of the page; you can see if it's been translated or not. For me, Twitter has, but the email and FB are still in English.

**Comment by damiankay** [comment] 2016-08-30 17:13
@jendc123 these translations are in Bablic, but are not appearing in the Petition site. This is a very high priority. Please have George look into this with @ScottDowne asap.

**Comment by ScottDowne** [comment] 2016-08-30 17:44
I took a look and did some googling, no help yet.

This is a test: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fmozillafoundation.nationbuilder.com%2F%3Flocale%3Dfr

We need the og:description to changed based on the query string, but it strongly suggests that the data is purely url based, and I definitely don't see the facebook crawler handling picking up any client side changes.

Facebook has an API for this, but I am unfamiliar with it. We could in theory redo the way we do tags, and it might work. Might have the same issue though, as it's hard to confirm if they even look at the query strings.

I have just reached out to bablic and hoping for an answer. I find it hard to believe we're the only people using bablic to request this.

**Comment by ScottDowne** [comment] 2016-08-30 18:41
It looks like you can manage the content outside of our page, and inside the Facebook dashboard for the app.

https://developers.facebook.com/docs/internationalization#manage

This would swap out the text or any tags, based on the facebook users language, and not the page language, which is fine. We would need to go in and manage the language in the dashboard for the app inside FB, and if we don't have one, we should create one. We do have an app id, so it's likely we have an app setup somewhere.

**Comment by jendc123** [comment] 2016-08-31 00:05
Hi @Melechuga @ScottDowne @valianttry @damiankay , 

We are still testing but looks like Facebook is localized. This is from our colleague in Argentina.
<img width="733" alt="skitch" src="https://cloud.githubusercontent.com/assets/6034476/18111356/f442eb6c-6eec-11e6-8f8b-163790289edb.png">

**Comment by ScottDowne** [comment] 2016-08-31 14:22
Yup, working for me too.

I had to clear cache, as there may be a case where get the new and old popups, one in English, and one in the desired language. I wouldn't worry about it, just an fyi if you see both, it's known, and should go away in time.

Closing! Any further quirks around this, if not the exact same issue, should be filed in a new ticket.

Thanks all! :rocket: :rocket: :rocket:

**Comment by damiankay** [comment] 2016-08-31 16:55
Huge win - thanks @jendc123!

**Comment by damiankay** [comment] 2016-08-31 21:17
I might have closed this too soon. @HPaulJohnson could you please test to ensure that email share messages are localized?

**Comment by HPaulJohnson** [comment] 2016-08-31 21:25
Tested and it works in Firefox but not Chrome (even in incognito to solve any caching issues). Someone else should test in Chrome and see if they can replicate.

Also, I'm seeing the headers and subhead all in English (and not translating when selecting non-English language) across both Firefox and Chrome.

**Comment by HPaulJohnson** [comment] 2016-08-31 21:28
The headline translation issue only appears to be happening on the "Reform Copyright" version of the header so might be an Optimizely issue. 

@vojtechmozilla @damiankay

**Comment by ScottDowne** [comment] 2016-08-31 21:30
Yeah, wow, email translation not working in Chrome. That's pretty weird, tbh. This shouldn't be a browser thing. I would be interested in knowing what's up when it's fixed :)

**Comment by vojtechsedlak** [comment] 2016-08-31 21:32
@HPaulJohnson  If you're seeing the Reform Copyright headline then it must be related to Optimizely, since that's one of tested variants. Switching between languages sadly interferes with the Optimizely script. Luckily it appears that less than 5% of people switch between languages after landing on the site.

**Comment by damiankay** [comment] 2016-08-31 21:45
@jendc123 @julienburns - we're still seeing English auto-fill for the Spanish email share. Can someone look into this asap please?

**Comment by valianttry** [comment] 2016-08-31 21:45
I just tested the email share from Spanish site (ES) and it still auto-fills a new email message with English text:

![don t_make_memes_illegal](https://cloud.githubusercontent.com/assets/9830371/18147465/8efe33e0-6f89-11e6-84ab-0c3bfbcb2c75.png)

I double checked in Bablic, and it is correctly pasted there in Espanol:

![visual_editor](https://cloud.githubusercontent.com/assets/9830371/18147433/71cac464-6f89-11e6-8cf2-cd30e8b40548.png)

**Closed as completed** 2016-09-01 20:25 UTC
Labels: bug, P1, Ready for QA, blocker
