### ISSUE TITLE
Email icon link does not function in Chrome (on share modal)

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#284] opened 2016-08-28 05:27 UTC
Browser: Chrome
Description: Email icon on share modal does not work.
Screen Shot 2016-08-27 at 10.29.22 PM

CC: @damiankay @valianttry @jendc123

**Comment by gholme4** [comment] 2016-08-30 05:17
Duplicate of #274

**Comment by HPaulJohnson** [comment] 2016-09-01 21:37
this is fixed.

**Closed as completed by HPaulJohnson** 2016-09-01 21:37 UTC
Labels: P1, Ready for QA
