### ISSUE TITLE
Design fundraising snippet variant for testing (EU NN)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#70] opened 2016-07-08 04:38 UTC
@lovegushwa and I met with Stephen Horlander who is on the Firefox desktop UX team about the donation snippet design. We agreed to test a few variants that are less disruptive for users, as recommended by Stephen. Variants we should test if possible when we launch an EU fundraiser in the snippet on July 21:
1. text-only snippet with blue linked donation ask (Simple)
2. default snippet design from EOY (buttons with amounts + red "Donate" button)
3. some version of # 2 above but with more muted elements / subtler design treatment

Copywriting for the snippets is happening in #69 
Next steps: @lovegushwa is going to chat with Stephen and mock up some options for # 3 above. NOTE: If time and capacity are too constrained, we can launch with a test of 1 and 2 variants and test a 3rd new variant when design capacity allows in the future.

**Comment by valianttry** [comment] 2016-07-13 00:22
@lovegushwa I think you're drowning and we should just run a test of 1 vs. 2 (e.g. no design required). We can revisit this test later on when things are less ?? 

That OK by you?
cc @damiankay

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by lovegushwa** [comment] 2016-07-28 16:56
@valianttry @damiankay will kick off some work on these next week.

**Comment by lovegushwa** [comment] 2016-08-15 21:27
@valianttry @vojtechmozilla  just to confirm, we already tested option 1 and option 2 above, but we need a design for option 3? ... Will we run a test of all three options again? ...

**Comment by vojtechsedlak** [comment] 2016-08-15 21:31
We did run a test between options 1 and 2, with the buttons version (option 1) dramatically increasing the likelihood of donation. As far as I know we need a design for option 3 that we should test against both option 1 and 2. I would prefer for all three options to be tested again, so that we don't compare results across different campaigns. Is that possible @valianttry? Hope that makes sense @lovegushwa. Let me know how I can support! Thanks

**Comment by damiankay** [comment] 2016-08-23 18:06
When are we hoping to complete this?

**Comment by lovegushwa** [comment] 2016-08-23 22:10
@damiankay @valianttry @vojtechmozilla 

Here are a few options. If these are good to go we lets select a few and have @ScottDowne build for a test. 

1 blue
<img width="1236" alt="test variant-snippet-blue-01" src="https://cloud.githubusercontent.com/assets/12228435/17917806/8d7435e4-6974-11e6-89c4-99b3ac76e9c8.png">

2 blue
<img width="1236" alt="test variant-snippet-blue-02" src="https://cloud.githubusercontent.com/assets/12228435/17917811/936db466-6974-11e6-853e-b6cb0b6c4880.png">

3 blue
<img width="1236" alt="test variant-snippet-blue-03" src="https://cloud.githubusercontent.com/assets/12228435/17917814/988f1aa2-6974-11e6-8dab-9fe975fa5f48.png">

4 blue
<img width="1236" alt="test variant-snippet_01-05" src="https://cloud.githubusercontent.com/assets/12228435/18059902/15c580f6-6dd0-11e6-9a89-5f8aa285e83c.png">

1 green
<img width="1236" alt="test variant-snippet-green-01" src="https://cloud.githubusercontent.com/assets/12228435/17917815/9ea53c00-6974-11e6-8fd8-d9e59e2873e6.png">

2 green
<img width="1236" alt="test variant-snippet-green-02" src="https://cloud.githubusercontent.com/assets/12228435/17917824/a3284074-6974-11e6-9c94-9bc6ff2f8c37.png">

3 green
<img width="1236" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/17917827/a7a66586-6974-11e6-842e-6937babefb84.png">

4 green
<img width="1236" alt="test variant-snippet_01-03" src="https://cloud.githubusercontent.com/assets/12228435/18059913/253399ec-6dd0-11e6-9dd2-d1f90810b84a.png">

1 red
<img width="1236" alt="test variant-snippet-red-01" src="https://cloud.githubusercontent.com/assets/12228435/17917899/22a737c4-6975-11e6-9a5e-582a7188113a.png">

2 red
<img width="1236" alt="test variant-snippet-red-02" src="https://cloud.githubusercontent.com/assets/12228435/17917903/275bdb1c-6975-11e6-89f6-e7924f322fac.png">

3 red
<img width="1236" alt="test variant-snippet-red-03" src="https://cloud.githubusercontent.com/assets/12228435/17917910/2d108c1a-6975-11e6-9554-7e25d65da259.png">

4 red
<img width="1236" alt="test variant-snippet_01-04" src="https://cloud.githubusercontent.com/assets/12228435/18059921/357060ec-6dd0-11e6-9d48-5728aba6f43c.png">

gray - one button
<img width="1236" alt="test variant-snippet_01-02" src="https://cloud.githubusercontent.com/assets/12228435/18059929/3ede080a-6dd0-11e6-9fb0-0cb28e25b456.png">

FOR CONTEXT, Last years optimized design we are testing a few of the above options against:
![screen shot 2016-08-24 at 2 31 31 pm](https://cloud.githubusercontent.com/assets/12228435/18060008/b8d71ab6-6dd0-11e6-8309-07c3de0ebfd2.png)

**Comment by valianttry** [comment] 2016-08-23 22:19
@lovegushwa may we have a variant with a red "donate" button for comparison? It will help us know whether it matters at all, and how much conversion we lose (if any) without using red.

**Comment by valianttry** [comment] 2016-08-23 22:34
also, @lovegushwa -- has Stephen on the Firefox UX team seen these at all? These are the fruit of your conversations with him? Just wondering if you should share them with him first or if you did already?

**Comment by lovegushwa** [comment] 2016-08-23 23:19
@valianttry we should share them with Steven, probably the best way to show him is in the context of the overall test. I'll flag him once I update with more colors.

**Comment by ScottDowne** [comment] 2016-08-26 17:33
Just taking a look at these now, but I wonder if it's too soon consider the design implications (if any) when the snippet is localized.

We don't have in context translations, so making translation decisions based on the designs can be tricky, and have slow turnaround.

Strings can become larger than the button space we have, that's more than enough for English. Can be solved by fixing the translation.

Currency changes are trickier because some language currency combinations can have large currency symbols, and some currencies have huge numbers for reasonable amounts. Example, Hungarian: https://donate.mozilla.org/hu/?currency=huf

**Comment by ScottDowne** [comment] 2016-08-26 17:38
I hope I am not adding too much noise to what's probably already a complex situation :( 

I wonder also if we should test a 3 or 2 button snippet? Maybe a snippet that's dynamic in the number of buttons it can display for amounts?

**Comment by valianttry** [comment] 2016-08-26 19:26
@ScottDowne maybe in the future. We're just testing slight design variations on the snippet we have used successfully first.

**Comment by lovegushwa** [comment] 2016-08-29 17:11
@valianttry just asking Stephen to take a look before we move ahead with a test.

**Comment by lovegushwa** [comment] 2016-08-31 22:20
@valianttry @vojtechmozilla 

No word from MOCO UX yet, but this is just a test so I think we are safe to move forward (snippet team should be able to review the designs we choose.)

@ScottDowne we should consider using this nifty opt-out UX Stephen Horlander shared:
http://people.mozilla.org/~shorlander/about-home-snippet-opt-out/about-home-test-02.html

(hint: mouse over the snippet)

**Comment by ScottDowne** [comment] 2016-08-31 22:53
@lovegushwa that isn't a currently built snippet, it seems. (it's not in the repo of snippets)

**Comment by lovegushwa** [comment] 2016-09-06 19:42
@ScottDowne @valianttry feedback from Stephen: 

Those all look really nice. 

For color choices I prefer the green/teal button because it has a contrast with the blue search button. I think we talked about the red button being usually reserved for error states? But that github issue seems to suggest using it just for testing purposes?

Looking forward to results :)

**Comment by lovegushwa** [comment] 2016-09-06 19:43
@ScottDowne @valianttry I responded and said colors are for a test, and Stephen seems cool with that. We should be ready to choose which we want to test and start building!

**Comment by valianttry** [comment] 2016-09-06 19:47
@lovegushwa one concern I have is that we have tested and know that long text yields statistically significant increases in conversion. The button to the right of a long block of text might look weird? Did you and Stephen talk about text length at all?

**Comment by lovegushwa** [comment] 2016-09-07 02:11
@valianttry no we did not discuss text length. We designed for really long text last year (a paragraph) and ended up using text that was two sentences if I remember right (the example above). We could do some variants of option 1 or 2 with a second sentence. I'm sure those design could also accommodate a paragraph.

**Comment by lovegushwa** [comment] 2016-09-07 21:18
@ScottDowne do you need anything to implement the opt out button? 
http://people.mozilla.org/~shorlander/about-home-snippet-opt-out/about-home-test-02.html

**Comment by ScottDowne** [comment] 2016-09-07 21:32
@lovegushwa there is already a snippet opt out button built in to the simple snippet, and it's not as polished as the example you provided.

I'm happy to polish it, so it's like the example, if that's something the snippet UX people are fine with me doing :) Looks like a fun little interaction, and it looks mostly done in that example. Make me wonder why it wasn't already done like that.

But there might also be a request for me to do it in a generic place (so in the simple snippet and our fundraising snippet), or specific to us (just the fundraising snippet), conversation.

**Comment by ScottDowne** [comment] 2016-09-07 22:42
Chatted with Jordan.

Looks like it shouldn't be an issue to polish the opt out button.

Looks like we'll need 1 new template for most of these tests, and we'll use the simple snippet with button for the other tests, which is already built.

I'll work on this Friday.

**Comment by valianttry** [comment] 2016-09-08 00:22
@ScottDowne yes please incorporate the improved UX for the opt out. I think they have just been iterating on improving that design. You know, things can always be more awesomer. 🏆 

@lovegushwa we used very long text late in the campaign. It's just a design consideration, but probably not for this immediate test scenario. We should use the same copy for each variant i think (I leave that thinking to @vojtechmozilla )

**Comment by lovegushwa** [comment] 2016-10-12 16:46
@ScottDowne @vojtechmzl 
Here is the heart icon for the test: 
https://drive.google.com/file/d/0B2qu3ExKWIlvWFJNR3hScWFRamM/view?usp=sharing

**Comment by lovegushwa** [comment] 2016-10-20 18:28
@vojtechmzl @ScottDowne based on the test results winner were going to see if we can optimize this years design to perform as well or better than the control: 

<img width="1093" alt="screen shot 2016-10-20 at 11 25 18 am" src="https://cloud.githubusercontent.com/assets/12228435/19572643/ffb358f4-96b7-11e6-8289-3e8032c0e3c0.png">

Variants to build:
Larger donate numbers
Exlpore how we highlight the amount (blue and or other color)
Highlight color / intensity
Test the size of the heart

**Comment by ScottDowne** [comment] 2016-10-20 20:42
My guess is the monthly checkbox in the 2015 being removed from the 2016 is the primary factor as to why the new snippet has better closure rate, but still got out performed by the 2015.

@vojtechmzl @lovegushwa

**Comment by vojtechsedlak** [comment] 2016-10-24 16:09
Hey @lovegushwa, did you have a chance to spin out any new variants for the fundraising snippet? Just want to see if we can land them before Mozfest. I know things are busy, so this can be picked up after Mozfest too. Thanks!

**Comment by ScottDowne** [comment] 2016-10-24 18:19
@vojtechmzl at the very least, blue selected amount button test can be enabled now.

**Comment by lovegushwa** [comment] 2016-10-25 17:47
@vojtechmzl here are the new variants, missing anything? 

<img width="1236" alt="test variant-snippet_02-01" src="https://cloud.githubusercontent.com/assets/12228435/19697448/38d06e4c-9aa0-11e6-82c1-8913c6793e41.png">

<img width="1236" alt="test variant-snippet_02-06" src="https://cloud.githubusercontent.com/assets/12228435/19697456/459a9ba2-9aa0-11e6-8ac5-99acf54057bd.png">

<img width="1236" alt="test variant-snippet_02-07" src="https://cloud.githubusercontent.com/assets/12228435/19697469/58cb8bf0-9aa0-11e6-8a8c-8e13ec9f4db7.png">

**Comment by lovegushwa** [comment] 2016-10-25 17:57
@ScottDowne ^

**Comment by vojtechsedlak** [comment] 2016-10-25 18:00
These look great @lovegushwa! Let's also remember to test the size of the heart icon (small vs. large).

**Comment by lovegushwa** [comment] 2016-10-25 18:06
@ScottDowne re. the heart comment. We can use this test variant above as the larger heart.
<img width="461" alt="screen shot 2016-10-25 at 11 03 02 am" src="https://cloud.githubusercontent.com/assets/12228435/19698083/b7f5a988-9aa2-11e6-8793-ee41712af1e4.png">

against the smaller heart 30x25px

<img width="787" alt="screen shot 2016-10-25 at 11 05 17 am" src="https://cloud.githubusercontent.com/assets/12228435/19698152/f17fb63a-9aa2-11e6-9346-8189b13f9707.png">

**Comment by ScottDowne** [comment] 2016-10-25 18:15
Great, most of this looks like it doesn't need to happen in the snippet template, which should save us some time.

We're running a test right now, so I don't see the rush of having this done before mozfest (it would be hard to do anyway)

@lovegushwa I notice the heart is vertically aligned to the top. Right now the snippet centers it vertically. Is it all the same to you if it's centered, or is moving it to the top an explicit change?

@vojtechmzl I think after the current test though, if it doesn't improve, we should push for testing a monthly checkbox before most of these variants. I'm putting all my chips on that being the cause. Just because we test it, and it proves that's why it was out performed, doesn't mean we use it, it just means we know WHY it was out performed.

**Comment by vojtechsedlak** [comment] 2016-10-25 18:27
good call on testing monthly checkbox @ScottDowne. I factored it in when evaluating the initial results, since having the checkbox indeed increases chance of a monthly donation, but running the test would help illuminate the impact on one-time donations specifically.

**Comment by ScottDowne** [comment] 2016-10-25 18:36
We can also disable it in the control and get the same idea as to it's effect vs the effect of the new snippet.

**Comment by lovegushwa** [comment] 2016-10-25 23:02
@ScottDowne my preference is the top, in the end the copy will be different lengths so aligning to the top line works best (it's a good way to catch a user eye and help them start reading the paragraph) ... however do what you need to do get this test up and running. We can optimize the UI later if it's a heavy lift.

**Comment by ScottDowne** [comment] 2016-10-26 15:45
Tis all good and easy. I can do it, just making sure it was an explicit
change.

**Comment by ScottDowne** [comment] 2016-11-03 15:37
@lovegushwa I thought we removed the highlight text because it was disruptive? I noticed it's crept its way back.

We also removed the monthly checkbox because it was disruptive, right? If I have to pick, I would pick the monthly checkbox over highlight text.

**Comment by valianttry** [comment] 2016-11-07 04:40
@vojtechmzl this ticket is getting a bit long / convoluted, can you create a new ticket for the remainder of the testing? I want to make certain we have a scope and an end in sight given we are running out of time.

**Comment by lovegushwa** [comment] 2016-11-11 22:48
@ScottDowne the highlight boost performance significantly. This is all part of the testing plan @vojtechmzl worked out.

**Comment by ScottDowne** [comment] 2016-11-11 23:00
@lovegushwa yeah, don't worry, I've added the back the highlight Tuesday, Just needs to finish going through review.

**Comment by lovegushwa** [comment] 2016-11-14 18:05
@ScottDowne please use the text highlight # ffe7ac (not the bright yellow color we used last year.)

**Comment by vojtechsedlak** [comment] 2016-11-17 23:23
The latest round of designs is being tested next week. Closing this ticket. Results will be communicated through #333

**Closed as completed by vojtechsedlak** 2016-11-17 23:23 UTC
Labels: P1, Fundraising, design, snippet
